language: c
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
script: extras/build-tests/select-config $BUILDCONFIG && ./Config -quick && make
env:
  - BUILDCONFIG=""
  - BUILDCONFIG="system-cares"
  - BUILDCONFIG="system-cares system-curl"
  - BUILDCONFIG="local-curl"
